# Generated by Django 4.2.9 on 2026-04-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('bus_type', models.CharField(choices=[('sleeper', 'Sleeper'), ('semi_sleeper', 'Semi Sleeper'), ('seater', 'Seater'), ('ac_sleeper', 'AC Sleeper'), ('ac_seater', 'AC Seater'), ('luxury', 'Luxury'), ('volvo', 'Volvo AC')], max_length=30)),
                ('total_seats', models.IntegerField(default=40)),
                ('amenities', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='operators/')),
                ('rating', models.DecimalField(decimal_places=2, default=4.0, max_digits=3)),
                ('total_trips', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.FloatField()),
                ('estimated_duration', models.DurationField()),
                ('popular', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_seats', models.IntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='buses.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='buses.route')),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='buses.busoperator'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('window', 'Window'), ('aisle', 'Aisle'), ('middle', 'Middle'), ('lower_berth', 'Lower Berth'), ('upper_berth', 'Upper Berth')], default='window', max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('extra_charge', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.trip')),
            ],
            options={
                'unique_together': {('trip', 'seat_number')},
            },
        ),
    ]
