# Generated by Django 4.2.9 on 2026-04-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route', 'departure_time'], name='buses_trip_route_i_32ec04_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='buses_trip_status_d63579_idx'),
        ),
    ]
